### ISSUE TITLE
es6.generators vs. regenerator?

### ISSUE THREAD

**Issue by elierotenberg** [hax/babel-features#2]
I don't think there is an `es6.generators` in babel. Did you mean `regenerator`?

**Comment by hax** [comment]
Yes there is no `es6.generators` in babel.
I introduced it for apply `asyncToGenerator` transformer instead of `regenerator` in Node.js 0.11+ env which already support generators.

But ES2015 spec require `Generator.prototype.return` method which V8 have not implemented, so for maximal compatibility, the `options()` method will always give `regenerator` for Node.js up to now.

**Comment by hax** [comment]
See https://github.com/alekseykulikov/babel-preset-es2015-node5/issues/3 for more discussion about whether we should use `regenerator`.

**Comment by hax** [comment]
[2.x](https://github.com/hax/babel-features/tree/2.x) introduced `es2015-generator-return` and map to [babel-plugin-transform-es2015-generator-return](https://www.npmjs.com/package/babel-plugin-transform-es2015-generator-return)
